version: '3'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana.db:/etc/grafana/grafana.db
      - ./grafana.ini:/etc/grafana/grafana.ini

  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100

volumes:
  prometheus-data:
