server:
  http_listen_port: 9797
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: https://7046:eyJrIjoiYTUwZWJlNDczY2Q3ZjcxYTVmMzVhMWZmNjBmNTEyYzI1N2E1ZWJjOSIsIm4iOiJsb2dzIiwiaWQiOjQyMzA3MX0=@logs-prod-us-central1.grafana.net/api/prom/push

scrape_configs:
- job_name: system
  pipeline_stages:
  - docker:
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
